### ISSUE TITLE
Minibridge

### ISSUE THREAD

**Issue by rulojuka** [rulojuka/sbking#20]
Implement minibridge according to [Wikipedia](https://en.wikipedia.org/wiki/Minibridge) rules.

**Comment by rulojuka** [comment]
Flow according to Taís:

- HCP will not be shown at any time.
- After dealing, there will be a button shown only to the owner of the table. Clicking that button will show the cards of the Dummy to the Declarer
- After hitting that button, the Declarer will be shown 2 forms to answer:
First one: A strain
Second one: A number from 1 to 7.
- Dummy will only be shown to everyone after the exit card.
- The Dummy will lose control of its own cards and the Declarer will gain control of Dummy's cards.

The hands should be dealt again indefinitely

**Comment by TaisBattaggia** [comment]
morto ver as cartas do carteador depois da saída

**Comment by TaisBattaggia** [comment]
Colocar as cartas do trunfo na esquerda.

**Comment by rulojuka** [comment]
> Colocar as cartas do trunfo na esquerda.

Vou usar a seguinte ordenação:

(:spades:) : :spades:,:hearts:,:clubs:,:diamonds:
(:hearts:) : :hearts:,:spades:,:diamonds:,:clubs:
(:diamonds:) : :diamonds:,:spades:,:hearts:,:clubs:
(:clubs:) : :clubs:,:hearts:,:spades:,:diamonds:

ok?

**Comment by TaisBattaggia** [comment]
Ok. Como você achar melhor.

**Comment by rulojuka** [comment]
Finished at f5d690ed06234cd082635cc72bfa2f2a41904bb6
