### ISSUE TITLE
feat: undo

### ISSUE THREAD

**Issue by rulojuka** [rulojuka/sbking#24]
Make possible to undo actions, mainly the playing of a card but eventually also auction related actions.

**Comment by aateg** [comment]
- Direction clicks on button "Undo"
- Undo every card up to (including) my last action

**Comment by aateg** [comment]
### Coding description

- Add method `undo` to ClientToServerMessageSender.java that sends the string "UNDO"
- Add if else statement in ClientGameSocket.java that map "UNDO" message into functionality of Table class
