### ISSUE TITLE
(2) Criação de uma LobbyScreen

### ISSUE THREAD

**Issue by rulojuka** [rulojuka/sbking#76]
Inserção de uma tela vazia no meio do caminho (sem parar nela)
Essa tela deveria uma outra classe. Aí o fluxo seria algo do tipo:
NetworkClientScreen -> LobbyScreen -> `<Game>`ClientScreen

**Comment by aateg** [comment]
@rulojuka eu tive uma ideia.
Partindo da MainNetworkGame verificamos que lá é instanciada um `<Game>`ClientScreen. Minha sugetsão é que ali se crie a LobbyScreen e dê run nela na MainNetworkGame. 
Ainda não sei se é possível, após a escolha do jogo, criar um MinibridgeClientScreen dentro de uma Jframe que está rodando. Mas acredito que é importante pensando que o Lobby deveria chamar outras Screen de jogo.

A ideia acima transformaria a MainNetworkGame no seguinte.
`java
public static void main(String[] args) {
        ClientApplicationState.startAppState();
        LobbyScreen lobbyScreen = new LobbyScreen();
        lobbyScreen.run();
        LOGGER.info("Exiting main thread.");
    }
`
A LobbyScreen é responsável por pintar a tela de `Play!`, pintar a tela do Lobby e finalmente ir para tela do jogo `<Game>ClientScreen`.

Update: 
- Acabei de descobrir que não dá pra rodar Jframe dentro de Jframe https://stackoverflow.com/questions/17287248/jframe-inside-another-jframe . A sugestão é internal frames ou Jpanels
