### ISSUE TITLE
(2) Garantir que assim que existir uma mesa, todos os jogadores conectados entrarão (como spec) na mesa

### ISSUE THREAD

**Issue by rulojuka** [rulojuka/sbking#78]
- Server recebe uma mensagem do tipo CreateTableMessage e cria uma mesa de acordo com o parâmetro recebido. (gameName)
-SBKingServer que sabe as pessoas conectadas e se existe uma mesa criada.
- Quando a mesa for criada
      - "manda" todas as pessoas pra mesa
        - dá um addSpectator() de todo mundo na Table
        - Envia uma mensagem de "mudou pra table" para todos esses clientes
      - "redireciona" todas as novas conexões pra mesa

**Comment by aateg** [comment]
provavelmente vai ser implementado no KryonetSbkingServer -> tem todas as connections.
- Criar nova table
- E dar um addSpectator das connections
